# Generated by Django 5.1.6 on 2026-01-22 11:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="템플릿 이름", max_length=200)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("intro", "Introduction"),
                            ("demo", "Demo Request"),
                            ("partnership", "Partnership"),
                            ("followup", "Follow-up"),
                            ("other", "Other"),
                        ],
                        default="intro",
                        help_text="템플릿 목적",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="활성화 여부"),
                ),
            ],
            options={
                "db_table": "template",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TemplateVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.IntegerField(help_text="버전 번호")),
                ("subject_tpl", models.TextField(help_text="제목 템플릿")),
                ("body_tpl", models.TextField(help_text="본문 템플릿")),
                (
                    "format",
                    models.CharField(
                        choices=[("html", "HTML"), ("text", "Plain Text")],
                        default="text",
                        help_text="포맷",
                        max_length=10,
                    ),
                ),
                (
                    "subject_length",
                    models.IntegerField(blank=True, help_text="제목 길이", null=True),
                ),
                (
                    "body_length",
                    models.IntegerField(blank=True, help_text="본문 길이", null=True),
                ),
                (
                    "cta_type",
                    models.CharField(
                        choices=[
                            ("reply", "Reply"),
                            ("link", "Link"),
                            ("none", "None"),
                        ],
                        default="none",
                        help_text="CTA 타입",
                        max_length=10,
                    ),
                ),
                (
                    "personalization_level",
                    models.SmallIntegerField(default=0, help_text="개인화 수준 (0-2)"),
                ),
                (
                    "template",
                    models.ForeignKey(
                        help_text="템플릿",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="templates.template",
                    ),
                ),
            ],
            options={
                "db_table": "template_version",
                "ordering": ["-version"],
                "indexes": [
                    models.Index(
                        fields=["template", "version"],
                        name="template_ve_templat_a85850_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("template", "version"), name="unique_template_version"
                    )
                ],
            },
        ),
    ]
