# Generated by Django 5.1.6 on 2026-01-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="templateversion",
            name="attachment_name",
            field=models.CharField(
                blank=True,
                help_text="첨부파일 이름 (예: 제품카탈로그.pdf)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="templateversion",
            name="attachment_url",
            field=models.URLField(
                blank=True,
                help_text="첨부파일 URL (예: https://cdn.example.com/file.pdf)",
                max_length=500,
                null=True,
            ),
        ),
    ]
