# Generated by Django 5.1.6 on 2026-01-22 11:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="태그명 (예: 유튜버, 게임, KPOP)",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "db_table": "tag",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[("youtube", "YouTube")],
                        default="youtube",
                        help_text="플랫폼 (추후 확장 대비)",
                        max_length=20,
                    ),
                ),
                ("channel_name", models.CharField(help_text="채널명", max_length=255)),
                ("channel_url", models.URLField(help_text="채널 URL", max_length=500)),
                (
                    "subscriber_count",
                    models.BigIntegerField(
                        blank=True, db_index=True, help_text="구독자 수", null=True
                    ),
                ),
                (
                    "primary_email",
                    models.EmailField(
                        blank=True,
                        help_text="빠른 조회용 메일",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "keywords_raw",
                    models.TextField(
                        blank=True, help_text="콤마 구분 키워드 문자열", null=True
                    ),
                ),
                (
                    "keywords_norm",
                    models.JSONField(
                        blank=True, help_text="정규화된 키워드 배열", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("qualified", "Qualified"),
                            ("do_not_contact", "Do Not Contact"),
                        ],
                        db_index=True,
                        default="new",
                        help_text="리드 상태",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="메모", null=True)),
            ],
            options={
                "db_table": "lead",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["subscriber_count"], name="lead_subscri_248909_idx"
                    ),
                    models.Index(fields=["status"], name="lead_status_e8cfda_idx"),
                    models.Index(
                        fields=["primary_email"], name="lead_primary_8d3adc_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("platform", "channel_url"),
                        name="unique_platform_channel",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Suppression",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("domain", "Domain"),
                            ("lead", "Lead"),
                        ],
                        help_text="차단 타입",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="차단 값 (email, domain, lead UUID)", max_length=500
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("unsubscribe", "Unsubscribe"),
                            ("complaint", "Complaint"),
                            ("bounce", "Bounce"),
                            ("manual", "Manual"),
                        ],
                        help_text="차단 사유",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "suppression",
                "indexes": [
                    models.Index(
                        fields=["type", "value"], name="suppression_type_273abc_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("type", "value"), name="unique_suppression"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LeadTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead_tags",
                        to="crm.lead",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead_tags",
                        to="crm.tag",
                    ),
                ),
            ],
            options={
                "db_table": "lead_tag",
                "indexes": [
                    models.Index(fields=["tag"], name="lead_tag_tag_id_716c51_idx"),
                    models.Index(fields=["lead"], name="lead_tag_lead_id_658874_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("lead", "tag"), name="unique_lead_tag"
                    )
                ],
            },
        ),
    ]
