# Generated by Django 5.2 on 2026-01-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="tags",
            field=models.ManyToManyField(
                help_text="태그",
                related_name="leads",
                through="crm.LeadTag",
                to="crm.tag",
            ),
        ),
    ]
