# Generated by Django 5.1.6 on 2026-01-22 11:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0001_initial"),
        ("templates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="캠페인 이름", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("finished", "Finished"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="캠페인 상태",
                        max_length=20,
                    ),
                ),
                (
                    "daily_cap",
                    models.IntegerField(default=50, help_text="일일 발송 제한"),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Seoul", help_text="타임존", max_length=50
                    ),
                ),
                (
                    "frozen_at",
                    models.DateTimeField(
                        blank=True, help_text="대상 확정 시점", null=True
                    ),
                ),
                (
                    "frozen_target_count",
                    models.IntegerField(
                        blank=True, help_text="확정된 대상 수", null=True
                    ),
                ),
            ],
            options={
                "db_table": "campaign",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("lark", "Lark Suite")],
                        default="lark",
                        help_text="발송 제공자",
                        max_length=20,
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True,
                        help_text="제공자 메시지 ID",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "from_email",
                    models.EmailField(
                        blank=True, help_text="발신 이메일", max_length=254, null=True
                    ),
                ),
                (
                    "to_email",
                    models.EmailField(help_text="수신 이메일", max_length=254),
                ),
                ("subject_final", models.TextField(help_text="렌더된 제목")),
                (
                    "body_final",
                    models.TextField(blank=True, help_text="렌더된 본문", null=True),
                ),
                (
                    "body_hash",
                    models.CharField(
                        blank=True, help_text="본문 해시", max_length=64, null=True
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, db_index=True, help_text="발송 시간", null=True
                    ),
                ),
                (
                    "send_status",
                    models.CharField(
                        choices=[("sent", "Sent"), ("failed", "Failed")],
                        help_text="발송 상태",
                        max_length=20,
                    ),
                ),
                (
                    "failure_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("invalid_recipient", "Invalid Recipient"),
                            ("rate_limit", "Rate Limit"),
                            ("provider_error", "Provider Error"),
                            ("other", "Other"),
                        ],
                        help_text="실패 타입",
                        max_length=30,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "email_message",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadSegment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="세그먼트 이름", max_length=200)),
                ("filter_json", models.JSONField(help_text="필터 조건 DSL")),
            ],
            options={
                "db_table": "lead_segment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "snapshot",
                    models.JSONField(
                        blank=True, help_text="당시 리드 정보 스냅샷", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("replied", "Replied"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="대상 상태",
                        max_length=20,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        help_text="캠페인",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        help_text="리드",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_targets",
                        to="crm.lead",
                    ),
                ),
            ],
            options={
                "db_table": "campaign_target",
            },
        ),
        migrations.CreateModel(
            name="EmailEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("opened_pixel", "Opened (Pixel)"),
                            ("clicked", "Clicked"),
                            ("replied", "Replied"),
                            ("bounced", "Bounced"),
                        ],
                        help_text="이벤트 타입",
                        max_length=20,
                    ),
                ),
                (
                    "event_at",
                    models.DateTimeField(db_index=True, help_text="이벤트 발생 시간"),
                ),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        help_text="이벤트 메타데이터 (clicked_url, user_agent 등)",
                        null=True,
                    ),
                ),
                (
                    "email_message",
                    models.ForeignKey(
                        help_text="이메일 메시지",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="campaigns.emailmessage",
                    ),
                ),
            ],
            options={
                "db_table": "email_event",
                "ordering": ["-event_at"],
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="segment",
            field=models.ForeignKey(
                blank=True,
                help_text="세그먼트",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="campaigns.leadsegment",
            ),
        ),
        migrations.CreateModel(
            name="SendJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "to_email",
                    models.EmailField(help_text="수신 이메일", max_length=254),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(db_index=True, help_text="예약 시간"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("processing", "Processing"),
                            ("sent", "Sent"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="scheduled",
                        help_text="잡 상태",
                        max_length=20,
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        blank=True, help_text="처리 잠금 시간", null=True
                    ),
                ),
                (
                    "attempt_count",
                    models.IntegerField(default=0, help_text="시도 횟수"),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True, help_text="마지막 에러 메시지", null=True
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        help_text="캠페인",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="send_jobs",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "campaign_target",
                    models.ForeignKey(
                        help_text="캠페인 대상",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="send_jobs",
                        to="campaigns.campaigntarget",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        help_text="리드 (조회 최적화용)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="send_jobs",
                        to="crm.lead",
                    ),
                ),
                (
                    "template_version",
                    models.ForeignKey(
                        help_text="템플릿 버전",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="send_jobs",
                        to="templates.templateversion",
                    ),
                ),
            ],
            options={
                "db_table": "send_job",
                "ordering": ["scheduled_at"],
            },
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="send_job",
            field=models.OneToOneField(
                help_text="발송 잡",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_message",
                to="campaigns.sendjob",
            ),
        ),
        migrations.AddIndex(
            model_name="campaigntarget",
            index=models.Index(
                fields=["campaign", "status"], name="campaign_ta_campaig_507843_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaigntarget",
            index=models.Index(fields=["lead"], name="campaign_ta_lead_id_4e47e4_idx"),
        ),
        migrations.AddConstraint(
            model_name="campaigntarget",
            constraint=models.UniqueConstraint(
                fields=("campaign", "lead"), name="unique_campaign_lead"
            ),
        ),
        migrations.AddIndex(
            model_name="emailevent",
            index=models.Index(
                fields=["event_type", "event_at"], name="email_event_event_t_b82352_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailevent",
            index=models.Index(
                fields=["email_message", "event_type", "event_at"],
                name="email_event_email_m_e4957b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(fields=["status"], name="campaign_status_6dfdd9_idx"),
        ),
        migrations.AddIndex(
            model_name="sendjob",
            index=models.Index(
                fields=["status", "scheduled_at"], name="send_job_status_a1b50a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sendjob",
            index=models.Index(
                fields=["campaign", "status"], name="send_job_campaig_a615a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["sent_at"], name="email_messa_sent_at_dbea8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["to_email", "sent_at"], name="email_messa_to_emai_e70895_idx"
            ),
        ),
    ]
